name: "Keepalive Event"

on:
  schedule:
    - cron: '0 22 */1 * *'
  workflow_dispatch:

jobs:
  ubuntu-test:
    env:
      MESSAGE: ":robot: Keepalive Action"
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: "Keepalive Action"
        uses: k5-mot/keepalive-action@main
        with:
          MESSAGE: "${{env.MESSAGE}}"
          GITHUB_TOKEN: ${{env.GITHUB_TOKEN}}

